### ISSUE TITLE
Doctors can add their specializations

### ISSUE THREAD

**Issue by robocopkaka** [RubyConf-NG/openemrs#4]
---
name: 🚀 Doctors can add specializations to their accounts
about: Allow doctors add or update their specializations 💡
---

**Context**

When doctors are signing up, they should be able to enter their specialization(s?). Since `specializations` would be a different table, specializations should likely be added via a callback. Consider rolling back doctor created if specialization fails or notifying the user that the specialization creation failed and notifying them to update it in another action

**Dependencies**
* https://github.com/RubyConf-NG/openemrs/issues/3

*As* Doctor
*I want* to be able to sign up using a specialization
*And* I also want to be able to update my specialization
*So that* it can show up on my profile

---
Acceptance Criteria
---

*When* A doctor signs up or updates their specialization
*then* it should show up in their profiles

---
Notes
---

* Would need to update the doctor's serializer to fetch their specialization before returning a response

**Comment by igbanam** [comment]
How is this different from "Patients can update accounts"? I'm guessing just the endpoint that's gonna be different?

**Comment by robocopkaka** [comment]
Might not need this soon since we'd let all doctors have the same specialization. Had originally envisioned that specializations would be tracked on a different table when I came up up with this. Closing this for now
