### ISSUE TITLE
Users authentication

### ISSUE THREAD

**Issue by robocopkaka** [RubyConf-NG/openemrs#7]
---
name: 🚀 Authentication functionality
about: Allow users login into the platform 💡
---

**Context**

Currently users can sign up to the platform but can't sign in. Since we have different categories of user, having different authentication endpoints is something we can consider but not sure if its the best route to take from a security endpoint. I believe this is something that we should discuss so looping in @RubyConf-NG/opensource here.

We could have - `/doctors/login`, `/patients/login`,etc Or stick to a single `/login` route since emails would be unique. Using one means that the appropriate serializer to use would have to be set after the user is authenticated.

*As* User
*I want* to be login using my email address and password
*So that* I can have access to the system

---
Acceptance Criteria
---

*When* I login with valid credentials
*then* I should get a token/session ID back that I can authenticate future requests with

---
Considerations
---
* We should probably use JWT since most people are familiar with it. Alternative would be to track sessions with a table
* If using JWT, Should we use a gem here, i.e https://github.com/nsarno/knock or roll our own JWT authentication system from scratch

**Comment by igbanam** [comment]
Consider Clearance from thoughtbot

**Comment by robocopkaka** [comment]
Adding the link to `clearance` here - https://github.com/thoughtbot/clearance

**Comment by abruzy** [comment]
@robocopkaka can you assign this task to me, sign in
